/** Declaration file generated by dts-gen */

export = markdown_it_math;

declare function markdown_it_math(md: any, options: any): any;

declare namespace markdown_it_math {
    const prototype: {
    };

}

